/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ims.api.jakarta;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.Banner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import com.ims.api.jakarta.dao.repository.ApiCredentialRepository;
import com.ims.api.jakarta.entities.ApiCredentials;

/**
 * Please visit my personal web page
 * 	https://my.name.is.sandy.id
 * or you can direct message me to 
 * 	sandyharyono@gmail.com
 * 
 * */




@SpringBootApplication
public class App implements CommandLineRunner{
	
	@Autowired
	private ApiCredentialRepository apiDao;
	
	 
	/**
	 * The frist class that automatically called
	 * @param args
	 */
	public static void main(String[] args) {
		SpringApplication app = new SpringApplication(App.class);
        app.setBannerMode(Banner.Mode.OFF);
        app.run(args);
    }

	@Override
	public void run(String... args) throws Exception {
		
		
		Collection<GrantedAuthority> authorities = new ArrayList<GrantedAuthority>();
		authorities.add((new SimpleGrantedAuthority("USER_ADMIN")));
	 
		ArrayList<ApiCredentials> creds 
		= new ArrayList<ApiCredentials>(Arrays.asList( 
				new ApiCredentials("my_name_is_sandy",
				"$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6",authorities),
				
				new ApiCredentials("another_api_user",
						"$2a$10$TtNVNYfDIgQXk8LolbJuDe3uSDmw0Qdze8/HcOeq11OKjcvi0HAmy",authorities)) 
						);
		
		creds.forEach(cr -> 
			apiDao.save(cr)
		);
		
		
			
		
	}
	
	 
	
}
